In [4]:
import torch


In [5]:
#tensor is a general form for a number,vector, matrix or any n dimensional array



In [8]:
#number
t1=torch.tensor(4.)  #4. is a shortcut to 4.0 indicating python we want to create a floating point number
t1

tensor(4.)

In [9]:
t1.dtype

torch.float32

In [11]:
#Vector-is an array or list of numbers
#tensor require all its elements to have single data type
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [13]:
#Matrix
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [15]:
#3-dimensional array
t4=torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
    [17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [16]:
t1.shape  #as it is a scalar no dimensions

torch.Size([])

In [17]:
t2.shape  #an array with 4 elements

torch.Size([4])

In [18]:
t3.shape #3 elements each of ehich has 2 elements

torch.Size([3, 2])

In [20]:
t4.shape #2 elements having each 2 elements which have 3 elements each

torch.Size([2, 2, 3])

In [41]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

#setting requires_grad to true allows you to store the drivative when these values are used in an equation
#allows to calculate the derivative with respect to that variable of the entire equation
#but after the command .backward() is used

In [42]:
y=w*x+b
y


tensor(17., grad_fn=<AddBackward0>)

In [43]:
y.backward()  #looks backward and sees which of the inputs have requires_grad=True
#wherever it finds requires_grad=True it will insert the gradient of the output 

In [46]:
#gradient is another rerm for derivatices
#.grad stands for gradient
print("dy/dx:",x.grad)  #None as requires_grad was not set to True
print("dy/dw:",w.grad)
print("dy/db:",b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [48]:
import numpy as np

In [50]:
x=np.array([[1,2],[3,4.]])  #to create an array
x

array([[1., 2.],
       [3., 4.]])

In [51]:
y=torch.from_numpy(x)  #to convert numpy array to pytorch tensor
y 

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [54]:
x.dtype,y.dtype   #numpy and pytorch datatypes are written differently

(dtype('float64'), torch.float64)

In [56]:
z=y.numpy() #convert back to numpy array from pytorch tensor
z

array([[1., 2.],
       [3., 4.]])